# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantitem',
            name='closes_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurantitem',
            name='opens_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
